IMPALA-8307 Use test -x to check for ntp-wait
Running ntp-wait --help can return 0 or 1 depending on the
output of ntpq. For example:

$ sudo ntp-wait --help 2> /dev/null; echo $?
0
$ sudo killall ntpd
$ sudo ntp-wait --help 2> /dev/null; echo $?
1

This commit instead tests whether ntp-wait exists and is executable to
determine if it's installed.

Change-Id: I53c63dfa651ac242050171da70540d24c4caf32c
Reviewed-on: http://gerrit.cloudera.org:8080/12726
Reviewed-by: Joe McDonnell <joemcdonnell@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>

diff --git a/testdata/cluster/admin b/testdata/cluster/admin
--- a/testdata/cluster/admin
+++ b/testdata/cluster/admin
@@ -335,13 +335,16 @@ function start_cluster {
         NTP_CANARY=pool.ntp.org
         if ! ping -c 1 -w 5 "${NTP_CANARY}" >/dev/null 2>/dev/null; then
           echo "WARNING: cannot reach ${NTP_CANARY}; ntp sync recommended for Kudu"
-        # ntp-wait is in /usr/sbin on both CentOS and Debian-based systems, but regular
-        # users don't always have /usr/sbin in $PATH. Use the absolute path.
-        elif ! /usr/sbin/ntp-wait --help >/dev/null 2>/dev/null; then
-          echo "WARNING: ntp-wait not installed; ntp sync recommended for Kudu"
-        elif ! /usr/sbin/ntp-wait -v; then
-          echo "ntp-wait failed; cannot start kudu"
-          return 1
+        else
+          # ntp-wait is in /usr/sbin on both CentOS and Debian-based systems, but regular
+          # users don't always have /usr/sbin in $PATH. Use the absolute path.
+          ntp_wait=$(command -v ntp-wait || echo /usr/sbin/ntp-wait)
+          if [[ ! -x $ntp_wait ]]; then
+            echo "WARNING: ntp-wait not installed; ntp sync recommended for Kudu"
+          elif ! $ntp_wait -v; then
+            echo "ntp-wait failed; cannot start kudu"
+            return 1
+          fi
         fi
       fi
       start $SERVICE
